server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   #你本地的数据库用户名
    password: zysj1234 #你本地的数据库密码
    url: jdbc:mysql://bj-cdb-ay3sls6k.sql.tencentcdb.com:27534/elec_mart_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: localhost
    port: 6379
    password: ""
    timeout: 2000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  mail:
    host: smtp.qq.com                # QQ 邮箱 SMTP 服务器地址
    port: 465                        # SMTP 端口号（SSL）
    username: 1803573449@qq.com      # 发件人邮箱
    password: dffjphcblradbdcd         # QQ 邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

ip: localhost


